# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

# manual mode
branches:
  except:
    - /.*/


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: https://www.appveyor.com/docs/build-environment/#pre-installed-software
image: Visual Studio 2019

environment:
  REPO_DIR: &REPO_DIR c:\project  # directory created by appveyor

  SOL_FILE: nppAutoDetectIndent.sln
  MSBUILD_CMD_X86: /maxcpucount /property:Configuration=Release,Platform=x86
  MSBUILD_CMD_X64: /maxcpucount /property:Configuration=Release,Platform=x64

# clone directory
clone_folder: *REPO_DIR


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  - cd "%REPO_DIR%"
  - git submodule update --init --remote --recursive --depth 1

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd "%REPO_DIR%\src"
  - msbuild %SOL_FILE% %MSBUILD_CMD_X86%
  - msbuild %SOL_FILE% %MSBUILD_CMD_X64%

# scripts to run before deployment
after_build:
  - cd "%REPO_DIR%\src\Release"
  - 7z a -mx9 "x86.zip" "nppAutoDetectIndent.dll"
  - 'powershell -Command "& { $hash = (Get-FileHash -Algorithm SHA256 "x86.zip").hash.ToString().toLower(); Write-Host $hash " *x86.zip"; }" > "x86.zip.sha256"'
  - move "x86.zip" "%REPO_DIR%"
  - move "x86.zip.sha256" "%REPO_DIR%"
  - cd "%REPO_DIR%\src\x64\Release"
  - 7z a -mx9 "x64.zip" "nppAutoDetectIndent.dll"
  - 'powershell -Command "& { $hash = (Get-FileHash -Algorithm SHA256 "x64.zip").hash.ToString().toLower(); Write-Host $hash " *x64.zip"; }" > "x64.zip.sha256"'
  - move "x64.zip" "%REPO_DIR%"
  - move "x64.zip.sha256" "%REPO_DIR%"


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: x64.zip
    name: x64 plugin
  - path: x64.zip.sha256
    name: checksum
  - path: x86.zip
    name: x86 plugin
  - path: x86.zip.sha256
    name: checksum
